name: pipeline for web3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CONTRACT_DIRECTORY: ./truffle

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: compile_test
        run: echo "success"

  dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: iac
        run: echo "success"
      - name: deploy_contracts
        run: echo "success"
      - name: deploy_frontend
        run: echo "success"
      
  dev_validation:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: wait_for_dev_validation
        run: echo "success"
      - name: delete_dev
        run: echo "success"
  
  qa:
    runs-on: ubuntu-latest
    needs: dev_validation
    steps:
      - name: iac
        run: echo "success"
      - name: deploy_contracts
        run: echo "success"
      - name: deploy_frontend
        run: echo "success"
  
  qa_validation:
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: wait_for_qa_validation
        run: echo "success"
      - name: delete_qa
        run: echo "success"
    
  prod:
    runs-on: ubuntu-latest
    needs: qa_validation
    steps:
      - name: iac
        run: echo "success"
      - name: deploy_contracts
        run: echo "success"
      - name: deploy_frontend
        run: echo "success"
